import type { DelegationHandoff, RouteDecision } from "./types.js";

const validationHints = (): string[] => [
	"Inspect this repo's package.json, Makefile, or documentation for available script targets.",
	"Run the narrowest relevant formatter/typecheck/lint/test commands available in this repo.",
	"Report back if no suitable validation or testing setup exists.",
];

const executionPolicy = (tier: NonNullable<RouteDecision["tier"]>): string[] => {
	if (tier === "micro") {
		return [
			"Micro: no scout/context pass; read/edit exact allowed files only; run only requested or narrow validation; return compactly.",
		];
	}
	if (tier === "small") {
		return ["Small: optional scout only if target files are unclear; otherwise proceed directly with minimal task-scoped edits."];
	}
	if (tier === "medium") {
		return ["Medium: scout/context pass recommended before execution; then fix and validate once."];
	}
	return ["Full-auto: parent-orchestrated scout + plan + execute + review flow."];
};

export function buildDelegationHandoff(task: string, decision: RouteDecision): DelegationHandoff {
	const tier = decision.tier ?? "small";
	const allowedFiles = decision.signals.mentionedFiles.length > 0 ? decision.signals.mentionedFiles : ["<parent must confirm allowed files before launch>"];

	const prompt = [
		`Goal: ${task.trim()}`,
		"",
		`Conductor route: ${decision.route}`,
		decision.suggestedAgent ? `Suggested agent: ${decision.suggestedAgent}` : undefined,
		decision.suggestedModel ? `Preferred model: ${decision.suggestedModel}` : undefined,
		"",
		"Allowed files:",
		...allowedFiles.map((file) => `- ${file}`),
		"",
		"Parent decisions / implementation notes:",
		`- This is a ${tier} delegation handoff generated by Conductor.`,
		"- Keep the diff minimal and task-scoped.",
		"- Prefer existing project patterns over new abstractions.",
		"",
		"Execution policy / Context policy:",
		...executionPolicy(tier).map((policy) => `- ${policy}`),
		"",
		"Non-goals:",
		"- Do not redesign architecture beyond this task.",
		"- Do not touch unrelated files.",
		"- Do not commit, push, deploy, publish, reset, clean, or discard changes.",
		"",
		"Stop rules:",
		"- Stop and report if an unapproved product, API, architecture, security, persistence, or deployment decision is required.",
		"- Stop and report if the requested files/scope are insufficient.",
		"- If validation fails, make at most one focused fix attempt, then report status.",
		"",
		"Suggested validation:",
		...validationHints().map((command) => `- ${command}`),
		"",
		"Return format:",
		"Summary:",
		"Files Changed:",
		"Commands Run:",
		"Validation Result:",
		"Residual Risks:",
	].filter((line): line is string => typeof line === "string");

	return { decision, prompt: prompt.join("\n") };
}

export function formatHandoff(handoff: DelegationHandoff): string {
	return ["```text", handoff.prompt, "```"].join("\n");
}
